"""Add user_id to position modify

Revision ID: 45739a8fb9da
Revises: dcb4b1220c26
Create Date: 2024-11-28 16:50:13.665582

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "45739a8fb9da"
down_revision: Union[str, None] = "dcb4b1220c26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
