"""Add user_id to position fix2

Revision ID: 6c97de5f5774
Revises: a6f6045fdb33
Create Date: 2024-11-28 16:56:42.559091

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6c97de5f5774"
down_revision: Union[str, None] = "a6f6045fdb33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
