"""add task user relate

Revision ID: 74b12b8a69b8
Revises: a9b94c1181e4
Create Date: 2024-11-30 15:21:47.593382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74b12b8a69b8"
down_revision: Union[str, None] = "a9b94c1181e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
