"""position_description

Revision ID: 8ae32ebbf41b
Revises: a33e2c09f88d
Create Date: 2024-11-28 15:28:34.465507

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ae32ebbf41b"
down_revision: Union[str, None] = "a33e2c09f88d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
