"""fix: user-department relate

Revision ID: a33e2c09f88d
Revises: a8a33483796e
Create Date: 2024-11-27 18:30:39.392930

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a33e2c09f88d"
down_revision: Union[str, None] = "a8a33483796e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("path", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_departments_path"), ["path"], unique=False)

    with op.batch_alter_table("invite", schema=None) as batch_op:
        batch_op.drop_constraint("invite_email_key", type_="unique")
        batch_op.create_index(batch_op.f("ix_invite_email"), ["email"], unique=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("department_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "hashed_password", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.create_foreign_key(None, "departments", ["department_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "hashed_password", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.drop_column("department_id")

    with op.batch_alter_table("invite", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invite_email"))
        batch_op.create_unique_constraint("invite_email_key", ["email"])

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_path"))

    op.drop_table("departments")
    # ### end Alembic commands ###
