"""Initial migration

Revision ID: af7ff7983b34
Revises: 7cf2cad11883
Create Date: 2024-11-21 20:11:39.330426

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "af7ff7983b34"
down_revision: Union[str, None] = "7cf2cad11883"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
