"""Add user_id to position back

Revision ID: fd93f57e51fd
Revises: 6c97de5f5774
Create Date: 2024-11-28 17:00:43.149198

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd93f57e51fd"
down_revision: Union[str, None] = "6c97de5f5774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position", schema=None) as batch_op:
        batch_op.drop_constraint("position_user_id_fkey", type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "position_user_id_fkey", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###
